import { Student } from './types';

export const CLASSES = ['all', '9A', '9B', '10A', '10B', '11A', '11B', '12A', '12B'];

export const mockStudents: Student[] = [
    {
      id: 1,
      name: 'Rahul Kumar',
      email: 'rahul.kumar@schoolerp.in',
      photo: 'https://picsum.photos/seed/rahul/200/200.jpg',
      class: '10A',
      rollNo: '1001',
      phone: '+91 9876543210',
      grade: 'A+',
      status: 'active',
      admissionNo: '20240001',
      dateOfBirth: '2008-05-15',
      gender: 'Male',
      address: '123, Gandhi Nagar, Delhi - 110001',
      parentName: 'Rajesh Kumar',
      parentPhone: '+91 9876543210',
      parentEmail: 'rajesh.kumar@parent.com',
      enrollmentDate: '2024-04-01',
      board: 'CBSE',
      section: 'A',
      bloodGroup: 'B+',
      emergencyContact: '+91 9876543210',
      medicalConditions: 'None',
      fees: {
        total: 50000,
        paid: 45000,
        pending: 5000,
        lastPaymentDate: '2024-03-15'
      },
      academics: {
        gpa: 3.8,
        rank: 5,
        totalSubjects: 6,
        passedSubjects: 6,
        failedSubjects: 0
      },
      behavior: {
        disciplineScore: 85,
        incidents: 0,
        achievements: 3
      },
      attendance: {
        present: 165,
        absent: 8,
        late: 4,
        percentage: 94.2
      },
      documents: {
        birthCertificate: true,
        transferCertificate: true,
        medicalCertificate: true,
        aadharCard: true,
        passportPhoto: true,
        marksheet: true,
        casteCertificate: false,
        incomeCertificate: false
      },
      nationality: 'Indian',
      religion: 'Hindu',
      category: 'General',
      motherTongue: 'Hindi',
      city: 'Delhi',
      state: 'Delhi',
      pinCode: '110001',
      emergencyRelation: 'Father',
      admissionDate: '2024-04-01',
      previousSchool: '',
      previousClass: '',
      transferCertificate: '',
      fatherName: 'Rajesh Kumar',
      fatherOccupation: 'Business',
      fatherPhone: '+91 9876543210',
      fatherEmail: 'rajesh.kumar@parent.com',
      motherName: 'Sunita Kumar',
      motherOccupation: 'Teacher',
      motherPhone: '+91 9876543210',
      motherEmail: 'sunita.kumar@parent.com',
      guardianName: '',
      guardianRelation: '',
      guardianPhone: '',
      allergies: 'None',
      medications: 'None',
      doctorName: 'Dr. Sharma',
      doctorPhone: '+91 9876543210',
      transport: 'No',
      transportRoute: '',
      hostel: 'No',
      sibling: 'No',
      siblingName: '',
      siblingClass: '',
      aadharNumber: '123456789012',
      stsId: 'STS2024001',
      languageMedium: 'English'
    },
    {
      id: 2,
      name: 'Priya Sharma',
      email: 'priya.sharma@schoolerp.in',
      photo: 'https://picsum.photos/seed/priya/200/200.jpg',
      class: '10B',
      rollNo: '1002',
      phone: '+91 9876543211',
      grade: 'A',
      status: 'active',
      admissionNo: '20240002',
      dateOfBirth: '2008-08-22',
      gender: 'Female',
      address: '456, Nehru Street, Delhi - 110002',
      parentName: 'Anil Sharma',
      parentPhone: '+91 9876543211',
      parentEmail: 'anil.sharma@parent.com',
      enrollmentDate: '2024-04-01',
      board: 'CBSE',
      section: 'B',
      bloodGroup: 'O+',
      emergencyContact: '+91 9876543211',
      medicalConditions: 'Asthma',
      fees: {
        total: 50000,
        paid: 50000,
        pending: 0,
        lastPaymentDate: '2024-03-20'
      },
      academics: {
        gpa: 3.6,
        rank: 12,
        totalSubjects: 6,
        passedSubjects: 6,
        failedSubjects: 0
      },
      behavior: {
        disciplineScore: 92,
        incidents: 0,
        achievements: 5
      },
      attendance: {
        present: 170,
        absent: 5,
        late: 2,
        percentage: 96.1
      },
      documents: {
        birthCertificate: true,
        transferCertificate: true,
        medicalCertificate: true,
        aadharCard: true,
        passportPhoto: true,
        marksheet: true,
        casteCertificate: false,
        incomeCertificate: false
      },
      nationality: 'Indian',
      religion: 'Hindu',
      category: 'General',
      motherTongue: 'Hindi',
      city: 'Delhi',
      state: 'Delhi',
      pinCode: '110002',
      emergencyRelation: 'Father',
      admissionDate: '2024-04-01',
      previousSchool: '',
      previousClass: '',
      transferCertificate: '',
      fatherName: 'Anil Sharma',
      fatherOccupation: 'Engineer',
      fatherPhone: '+91 9876543211',
      fatherEmail: 'anil.sharma@parent.com',
      motherName: 'Meena Sharma',
      motherOccupation: 'Doctor',
      motherPhone: '+91 9876543211',
      motherEmail: 'meena.sharma@parent.com',
      guardianName: '',
      guardianRelation: '',
      guardianPhone: '',
      allergies: 'Asthma',
      medications: 'Inhaler',
      doctorName: 'Dr. Gupta',
      doctorPhone: '+91 9876543211',
      transport: 'No',
      transportRoute: '',
      hostel: 'No',
      sibling: 'No',
      siblingName: '',
      siblingClass: '',
      aadharNumber: '234567890123',
      stsId: 'STS2024002',
      languageMedium: 'Hindi'
    },
    {
      id: 3,
      name: 'Amit Patel',
      email: 'amit.patel@schoolerp.in',
      photo: 'https://picsum.photos/seed/amit/200/200.jpg',
      class: '9A',
      rollNo: '1003',
      phone: '+91 9876543212',
      grade: 'B+',
      status: 'active',
      admissionNo: '20240003',
      dateOfBirth: '2009-03-10',
      gender: 'Male',
      address: '789, Patel Colony, Delhi - 110003',
      parentName: 'Suresh Patel',
      parentPhone: '+91 9876543212',
      parentEmail: 'suresh.patel@parent.com',
      enrollmentDate: '2024-04-01',
      board: 'CBSE',
      section: 'A',
      bloodGroup: 'A+',
      emergencyContact: '+91 9876543212',
      medicalConditions: 'None',
      fees: {
        total: 48000,
        paid: 40000,
        pending: 8000,
        lastPaymentDate: '2024-03-10'
      },
      academics: {
        gpa: 3.2,
        rank: 25,
        totalSubjects: 6,
        passedSubjects: 5,
        failedSubjects: 1
      },
      behavior: {
        disciplineScore: 78,
        incidents: 2,
        achievements: 1
      },
      attendance: {
        present: 158,
        absent: 12,
        late: 6,
        percentage: 89.7
      },
      documents: {
        birthCertificate: true,
        transferCertificate: true,
        medicalCertificate: false,
        aadharCard: true,
        passportPhoto: true,
        marksheet: true,
        casteCertificate: false,
        incomeCertificate: false
      },
      nationality: 'Indian',
      religion: 'Hindu',
      category: 'OBC',
      motherTongue: 'Gujarati',
      city: 'Delhi',
      state: 'Delhi',
      pinCode: '110003',
      emergencyRelation: 'Father',
      admissionDate: '2024-04-01',
      previousSchool: '',
      previousClass: '',
      transferCertificate: '',
      fatherName: 'Suresh Patel',
      fatherOccupation: 'Shop Owner',
      fatherPhone: '+91 9876543212',
      fatherEmail: 'suresh.patel@parent.com',
      motherName: 'Rekha Patel',
      motherOccupation: 'Housewife',
      motherPhone: '+91 9876543212',
      motherEmail: 'rekha.patel@parent.com',
      guardianName: '',
      guardianRelation: '',
      guardianPhone: '',
      allergies: 'None',
      medications: 'None',
      doctorName: 'Dr. Patel',
      doctorPhone: '+91 9876543212',
      transport: 'No',
      transportRoute: '',
      hostel: 'No',
      sibling: 'No',
      siblingName: '',
      siblingClass: '',
      aadharNumber: '345678901234',
      stsId: 'STS2024003',
      languageMedium: 'Regional'
    },
    {
      id: 4,
      name: 'Sneha Reddy',
      email: 'sneha.reddy@schoolerp.in',
      photo: 'https://picsum.photos/seed/sneha/200/200.jpg',
      class: '11A',
      rollNo: '1004',
      phone: '+91 9876543213',
      grade: 'A+',
      status: 'active',
      admissionNo: '20230004',
      dateOfBirth: '2007-11-28',
      gender: 'Female',
      address: '321, Reddy Layout, Delhi - 110004',
      parentName: 'Prakash Reddy',
      parentPhone: '+91 9876543213',
      parentEmail: 'prakash.reddy@parent.com',
      enrollmentDate: '2023-04-01',
      board: 'CBSE',
      section: 'A',
      bloodGroup: 'AB+',
      emergencyContact: '+91 9876543213',
      medicalConditions: 'None',
      fees: {
        total: 55000,
        paid: 55000,
        pending: 0,
        lastPaymentDate: '2024-03-25'
      },
      academics: {
        gpa: 3.9,
        rank: 2,
        totalSubjects: 6,
        passedSubjects: 6,
        failedSubjects: 0
      },
      behavior: {
        disciplineScore: 95,
        incidents: 0,
        achievements: 8
      },
      attendance: {
        present: 175,
        absent: 2,
        late: 1,
        percentage: 98.3
      },
      documents: {
        birthCertificate: true,
        transferCertificate: true,
        medicalCertificate: true,
        aadharCard: true,
        passportPhoto: true,
        marksheet: true,
        casteCertificate: false,
        incomeCertificate: false
      },
      nationality: 'Indian',
      religion: 'Hindu',
      category: 'General',
      motherTongue: 'Telugu',
      city: 'Delhi',
      state: 'Delhi',
      pinCode: '110004',
      emergencyRelation: 'Father',
      admissionDate: '2023-04-01',
      previousSchool: '',
      previousClass: '',
      transferCertificate: '',
      fatherName: 'Prakash Reddy',
      fatherOccupation: 'Business',
      fatherPhone: '+91 9876543213',
      fatherEmail: 'prakash.reddy@parent.com',
      motherName: 'Lakshmi Reddy',
      motherOccupation: 'Teacher',
      motherPhone: '+91 9876543213',
      motherEmail: 'lakshmi.reddy@parent.com',
      guardianName: '',
      guardianRelation: '',
      guardianPhone: '',
      allergies: 'None',
      medications: 'None',
      doctorName: 'Dr. Reddy',
      doctorPhone: '+91 9876543213',
      transport: 'No',
      transportRoute: '',
      hostel: 'No',
      sibling: 'No',
      siblingName: '',
      siblingClass: '',
      aadharNumber: '456789012345',
      stsId: 'STS2023004',
      languageMedium: 'Bilingual'
    },
    {
      id: 5,
      name: 'Vikram Singh',
      email: 'vikram.singh@schoolerp.in',
      photo: 'https://picsum.photos/seed/vikram/200/200.jpg',
      class: '12B',
      rollNo: '1005',
      phone: '+91 9876543214',
      grade: 'B',
      status: 'suspended',
      admissionNo: '20220005',
      dateOfBirth: '2006-07-18',
      gender: 'Male',
      address: '654, Singh Enclave, Delhi - 110005',
      parentName: 'Mahendra Singh',
      parentPhone: '+91 9876543214',
      parentEmail: 'mahendra.singh@parent.com',
      enrollmentDate: '2022-04-01',
      board: 'CBSE',
      section: 'B',
      bloodGroup: 'B+',
      emergencyContact: '+91 9876543214',
      medicalConditions: 'None',
      fees: {
        total: 60000,
        paid: 30000,
        pending: 30000,
        lastPaymentDate: '2024-01-15'
      },
      academics: {
        gpa: 2.8,
        rank: 45,
        totalSubjects: 6,
        passedSubjects: 4,
        failedSubjects: 2
      },
      behavior: {
        disciplineScore: 45,
        incidents: 5,
        achievements: 0
      },
      attendance: {
        present: 140,
        absent: 25,
        late: 10,
        percentage: 79.5
      },
      documents: {
        birthCertificate: true,
        transferCertificate: false,
        medicalCertificate: false,
        aadharCard: true,
        passportPhoto: false,
        marksheet: false,
        casteCertificate: false,
        incomeCertificate: false
      },
      nationality: 'Indian',
      religion: 'Sikh',
      category: 'General',
      motherTongue: 'Punjabi',
      city: 'Delhi',
      state: 'Delhi',
      pinCode: '110005',
      emergencyRelation: 'Father',
      admissionDate: '2022-04-01',
      previousSchool: '',
      previousClass: '',
      transferCertificate: '',
      fatherName: 'Mahendra Singh',
      fatherOccupation: 'Business',
      fatherPhone: '+91 9876543214',
      fatherEmail: 'mahendra.singh@parent.com',
      motherName: 'Ranjit Kaur',
      motherOccupation: 'Housewife',
      motherPhone: '+91 9876543214',
      motherEmail: 'ranjit.kaur@parent.com',
      guardianName: '',
      guardianRelation: '',
      guardianPhone: '',
      allergies: 'None',
      medications: 'None',
      doctorName: 'Dr. Singh',
      doctorPhone: '+91 9876543214',
      transport: 'No',
      transportRoute: '',
      hostel: 'No',
      sibling: 'No',
      siblingName: '',
      siblingClass: '',
      aadharNumber: '567890123456',
      stsId: 'STS2022005',
      languageMedium: 'Urdu'
    }
  ];
